//export const apiKey = process.env.REACT_APP_API_KEY;
export const baseUrl = "https://api.themoviedb.org/3/";
export const imgNotFound = "./nomovie.jpg";
export const loading = "./loading.gif";
export const noResult = "./oopps.png";
export const defaultPage = 1;
export const appName = "MovieHub";
export const imgPath = "https://image.tmdb.org/t/p/";
export const youtubeUrl = "https://www.youtube.com/watch?v=";